# Generated by Django 5.2.11 on 2026-03-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pdf', models.FileField(upload_to='pdfs/')),
                ('page_image', models.ImageField(upload_to='extracted_pages/')),
                ('page_number', models.IntegerField()),
                ('embedding_blob', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
