# Generated by Django 5.2.11 on 2026-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduplicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='phash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
