# Generated by Django 5.2.11 on 2026-03-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduplicator', '0002_documentpage_phash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='embedding_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='page_image',
            field=models.ImageField(blank=True, null=True, upload_to='extracted_pages/'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
